# Generated by Django 4.0.6 on 2022-08-31 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_blockedip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blockedip',
            options={'verbose_name': 'BlockedIP', 'verbose_name_plural': 'BlockedIPs'},
        ),
    ]
