# Generated by Django 4.0.6 on 2022-09-04 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_navbar', models.BooleanField(default=True)),
                ('p_category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='Product.category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('in_sale', models.BooleanField(default=False)),
                ('discount', models.IntegerField(choices=[(5, '5'), (10, '10'), (15, '15'), (20, '20'), (25, '25'), (30, '30'), (35, '35'), (40, '40'), (45, '45'), (50, '50'), (55, '55'), (60, '60'), (65, '65'), (70, '70')])),
                ('new_price', models.FloatField(blank=True, null=True)),
                ('overview', models.TextField()),
                ('details', models.TextField()),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='Product.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Product_version',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='product_images')),
                ('quantity', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_version', to='Product.product')),
            ],
            options={
                'verbose_name': 'Product Version',
                'verbose_name_plural': 'Product Versions',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_review', models.IntegerField(choices=[(5, '100'), (3, '60'), (1, '20'), (4, '80'), (2, '40')])),
                ('value_review', models.IntegerField(choices=[(5, '100'), (3, '60'), (1, '20'), (4, '80'), (2, '40')])),
                ('quality_review', models.IntegerField(choices=[(5, '100'), (3, '60'), (1, '20'), (4, '80'), (2, '40')])),
                ('nickname', models.CharField(max_length=75)),
                ('summary', models.CharField(max_length=50)),
                ('product_review', models.TextField()),
                ('review_date', models.DateField(auto_now_add=True)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='Product.product_version')),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
            },
        ),
        migrations.CreateModel(
            name='ProductStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_statistic', to='Product.product_version')),
            ],
            options={
                'verbose_name': 'Product Statistic',
                'verbose_name_plural': 'Product Statistics',
            },
        ),
        migrations.CreateModel(
            name='Images_of_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='Product.product_version')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
