# Generated by Django 4.0.6 on 2022-09-04 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(2, '40'), (5, '100'), (4, '80'), (3, '60'), (1, '20')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(2, '40'), (5, '100'), (4, '80'), (3, '60'), (1, '20')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(2, '40'), (5, '100'), (4, '80'), (3, '60'), (1, '20')]),
        ),
    ]
