# Generated by Django 4.0.6 on 2022-09-04 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_alter_product_discount_alter_review_price_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_version',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='product',
            name='cover_image',
            field=models.ImageField(default=1, upload_to='product_images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(3, '60'), (4, '80'), (2, '40'), (5, '100'), (1, '20')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(3, '60'), (4, '80'), (2, '40'), (5, '100'), (1, '20')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(3, '60'), (4, '80'), (2, '40'), (5, '100'), (1, '20')]),
        ),
    ]
