# Generated by Django 4.0.6 on 2022-08-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_review_price_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(4, '80'), (3, '60'), (2, '40'), (5, '100'), (1, '20')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(4, '80'), (3, '60'), (2, '40'), (5, '100'), (1, '20')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(4, '80'), (3, '60'), (2, '40'), (5, '100'), (1, '20')]),
        ),
    ]
