# Generated by Django 4.0.6 on 2022-09-04 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_remove_product_version_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='version',
        ),
        migrations.AddField(
            model_name='review',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_review', to='Product.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(3, '60'), (5, '100'), (1, '20'), (2, '40'), (4, '80')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(3, '60'), (5, '100'), (1, '20'), (2, '40'), (4, '80')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(3, '60'), (5, '100'), (1, '20'), (2, '40'), (4, '80')]),
        ),
    ]
