# Generated by Django 4.0.6 on 2022-08-23 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_review_price_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(1, '20'), (2, '40'), (5, '100'), (4, '80'), (3, '60')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(1, '20'), (2, '40'), (5, '100'), (4, '80'), (3, '60')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(1, '20'), (2, '40'), (5, '100'), (4, '80'), (3, '60')]),
        ),
    ]
