# Generated by Django 4.0.6 on 2022-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_remove_product_date_product_version_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(4, '80'), (5, '100'), (2, '40'), (3, '60'), (1, '20')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(4, '80'), (5, '100'), (2, '40'), (3, '60'), (1, '20')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(4, '80'), (5, '100'), (2, '40'), (3, '60'), (1, '20')]),
        ),
        migrations.DeleteModel(
            name='Images_of_product',
        ),
        migrations.AddField(
            model_name='product_version',
            name='images',
            field=models.ManyToManyField(related_name='images_of_products', to='Product.image'),
        ),
    ]
