# Generated by Django 4.0.6 on 2022-09-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_category_name_az_category_name_en_product_name_az_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='details_az',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='details_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(1, '20'), (2, '40'), (5, '100'), (4, '80'), (3, '60')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(1, '20'), (2, '40'), (5, '100'), (4, '80'), (3, '60')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(1, '20'), (2, '40'), (5, '100'), (4, '80'), (3, '60')]),
        ),
    ]
