# Generated by Django 4.0.6 on 2022-08-23 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_remove_product_read_count_alter_review_price_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_version',
            name='read_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(4, '80'), (3, '60'), (5, '100'), (2, '40'), (1, '20')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(4, '80'), (3, '60'), (5, '100'), (2, '40'), (1, '20')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(4, '80'), (3, '60'), (5, '100'), (2, '40'), (1, '20')]),
        ),
    ]
