# Generated by Django 4.0.6 on 2022-08-23 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_alter_review_price_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[('20', '1'), ('100', '5'), ('60', '3'), ('80', '4'), ('40', '2')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[('20', '1'), ('100', '5'), ('60', '3'), ('80', '4'), ('40', '2')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[('20', '1'), ('100', '5'), ('60', '3'), ('80', '4'), ('40', '2')]),
        ),
    ]
