# Generated by Django 4.0.6 on 2022-11-17 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_alter_review_price_review_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_version',
            old_name='date',
            new_name='datetime',
        ),
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(5, '100'), (1, '20'), (3, '60'), (2, '40'), (4, '80')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(5, '100'), (1, '20'), (3, '60'), (2, '40'), (4, '80')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(5, '100'), (1, '20'), (3, '60'), (2, '40'), (4, '80')]),
        ),
    ]
