# Generated by Django 4.0.6 on 2022-08-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0011_alter_review_price_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(60, '3'), (80, '4'), (20, '1'), (40, '2'), (100, '5')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(60, '3'), (80, '4'), (20, '1'), (40, '2'), (100, '5')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(60, '3'), (80, '4'), (20, '1'), (40, '2'), (100, '5')]),
        ),
    ]
