# Generated by Django 4.0.6 on 2022-11-20 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0012_rename_date_product_version_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(2, '40'), (3, '60'), (1, '20'), (5, '100'), (4, '80')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(2, '40'), (3, '60'), (1, '20'), (5, '100'), (4, '80')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(2, '40'), (3, '60'), (1, '20'), (5, '100'), (4, '80')]),
        ),
    ]
