# Generated by Django 4.0.6 on 2022-08-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0013_alter_review_price_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_version',
            name='read_count',
        ),
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(1, '20'), (3, '60'), (5, '100'), (2, '40'), (4, '80')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(1, '20'), (3, '60'), (5, '100'), (2, '40'), (4, '80')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(1, '20'), (3, '60'), (5, '100'), (2, '40'), (4, '80')]),
        ),
    ]
