# Generated by Django 4.0.6 on 2022-08-25 09:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_remove_product_version_read_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='collection',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='Product.category'),
        ),
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(2, '40'), (4, '80'), (3, '60'), (1, '20'), (5, '100')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(2, '40'), (4, '80'), (3, '60'), (1, '20'), (5, '100')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(2, '40'), (4, '80'), (3, '60'), (1, '20'), (5, '100')]),
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
    ]
