# Generated by Django 4.0.6 on 2022-09-11 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0014_product_date_alter_review_price_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(4, '80'), (2, '40'), (3, '60'), (1, '20'), (5, '100')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(4, '80'), (2, '40'), (3, '60'), (1, '20'), (5, '100')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(4, '80'), (2, '40'), (3, '60'), (1, '20'), (5, '100')]),
        ),
    ]
