# Generated by Django 4.0.6 on 2022-08-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0016_product_version_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(1, '20'), (3, '60'), (5, '100'), (4, '80'), (2, '40')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(1, '20'), (3, '60'), (5, '100'), (4, '80'), (2, '40')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(1, '20'), (3, '60'), (5, '100'), (4, '80'), (2, '40')]),
        ),
    ]
