# Generated by Django 4.0.6 on 2022-08-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0018_alter_review_price_review_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productstatistic',
            options={'verbose_name': 'Product Statistic', 'verbose_name_plural': 'Product Statistics'},
        ),
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(1, '20'), (2, '40'), (5, '100'), (4, '80'), (3, '60')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(1, '20'), (2, '40'), (5, '100'), (4, '80'), (3, '60')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(1, '20'), (2, '40'), (5, '100'), (4, '80'), (3, '60')]),
        ),
    ]
