# Generated by Django 4.0.6 on 2022-08-31 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0021_alter_review_price_review_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_version',
            name='basket',
        ),
        migrations.AlterField(
            model_name='review',
            name='price_review',
            field=models.IntegerField(choices=[(4, '80'), (3, '60'), (5, '100'), (1, '20'), (2, '40')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='quality_review',
            field=models.IntegerField(choices=[(4, '80'), (3, '60'), (5, '100'), (1, '20'), (2, '40')]),
        ),
        migrations.AlterField(
            model_name='review',
            name='value_review',
            field=models.IntegerField(choices=[(4, '80'), (3, '60'), (5, '100'), (1, '20'), (2, '40')]),
        ),
    ]
