# Generated by Django 4.0.6 on 2022-09-18 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='short_desc',
        ),
    ]
