# Generated by Django 4.0.6 on 2022-08-18 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authors',
            options={'verbose_name': 'Author', 'verbose_name_plural': 'Authors'},
        ),
    ]
