# Generated by Django 4.0.6 on 2022-09-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_alter_comments_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authors',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
