# Generated by Django 4.0.6 on 2022-09-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0004_alter_authors_author_alter_comments_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='image',
            field=models.ImageField(default=1, upload_to='blog_category_images'),
            preserve_default=False,
        ),
    ]
