# Generated by Django 4.0.6 on 2022-09-18 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0005_categories_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='image',
        ),
    ]
