# Generated by Django 4.0.6 on 2022-09-23 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0004_alter_review_price_review_and_more'),
        ('Order', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket_item',
            name='product',
        ),
        migrations.AddField(
            model_name='basket_item',
            name='product',
            field=models.ManyToManyField(related_name='product_basket_item', to='Product.product_version'),
        ),
    ]
