# Generated by Django 4.0.6 on 2022-09-04 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0006_alter_review_price_review_and_more'),
        ('Order', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basket',
            name='product',
            field=models.ManyToManyField(related_name='products_basket', to='Product.product'),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='product_ver',
            field=models.ManyToManyField(related_name='products_wishlist', to='Product.product'),
        ),
    ]
