# Generated by Django 4.0.6 on 2022-09-23 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_review_price_review_and_more'),
        ('Order', '0003_remove_basket_item_product_basket_item_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basket_item',
            name='product',
        ),
        migrations.AddField(
            model_name='basket_item',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_basket_item', to='Product.product_version'),
        ),
    ]
