# Generated by Django 4.0.6 on 2022-08-31 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_basket_product_wishlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wishlist',
            old_name='product',
            new_name='product_ver',
        ),
    ]
